{-# OPTIONS --safe --cubical --guardedness #-}

-- ============================================================
-- Topos.AbstractionTiers — sufficient conditions for the two
-- tiers of the comparison map φB, over thin bases.
--
-- Fix a base functor F : C → D.  Two conditions on F:
--   BackCond∥: every coarse refinement of App₀ e merely lifts
--     to a fine refinement of e.  Causal reading: F hides no
--     refinements.  BackCond is the chosen-lift form.
--   ReflectAt c: every coarse arrow between images of
--     refinements of c comes from a fine arrow.  Causal
--     reading: F conflates no alternatives.  Reflect is the
--     global form.
--
-- TIER 1 (BackCond∥, D thin).  φB is injective (φB-inj) and
-- commutes with Heyting implication and negation (φB-⇒, φB-¬).
-- With the ⊤,⊥,∧,∨ facts of Topos.BaseChange, φB is then a
-- morphism of Heyting algebras.  The coarse internal logic
-- embeds in the fine one.
--
-- TIER 2 (add ReflectAt, C thin).  imageSieve is a two-sided
-- inverse of φB (φB-surjective, φB-retract).  So φB is a
-- bijection on truth values.
--
-- The conditions are equivalent to the conclusions, not only
-- sufficient.  Topos.TiersConverse proves the converses;
-- Topos.MergeAbstraction and Topos.HiddenRefinement are the
-- concrete instances where each condition fails.
-- ============================================================

module Topos.AbstractionTiers where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.HLevels using (hProp; isSetHProp)
open import Cubical.Data.Sigma using (Σ-syntax; _×_; _,_; fst; snd)
open import Cubical.Functions.Logic using (⇔toPath)
open import Cubical.HITs.PropositionalTruncation as PT using (∥_∥₁; ∣_∣₁; squash₁)

open import Topos.Cat
open import Topos.Omega
open import Topos.BaseChange
open import Topos.DoubleNegation using (_⇒S_; ¬S; ⊥S)

-- ------------------------------------------------------------
-- The two conditions on a base functor, and the image sieve.
-- ------------------------------------------------------------
module _ {ℓ} {C D : Precategory ℓ ℓ} (F : BaseFunctor C D) where
  private
    module Cc = Precategory C
    module Dc = Precategory D
  open BaseFunctor F

  -- Chosen lifts of coarse refinements.
  BackCond : Type ℓ
  BackCond = (e : Cc.Ob) (d' : Dc.Ob) (h : Dc.Hom d' (App₀ e))
           → Σ[ e' ∈ Cc.Ob ] Σ[ k ∈ Cc.Hom e' e ] (App₀ e' ≡ d')

  -- Mere lifts.  This is the form the converse direction
  -- produces, and it suffices for every theorem below.
  BackCond∥ : Type ℓ
  BackCond∥ = (e : Cc.Ob) (d' : Dc.Ob) (h : Dc.Hom d' (App₀ e))
            → ∥ Σ[ e' ∈ Cc.Ob ] Σ[ k ∈ Cc.Hom e' e ] (App₀ e' ≡ d') ∥₁

  ∣back∣ : BackCond → BackCond∥
  ∣back∣ b e d' h = ∣ b e d' h ∣₁

  -- Order reflection, anchored at a context c.
  ReflectAt : Cc.Ob → Type ℓ
  ReflectAt c = {x y : Cc.Ob} → Cc.Hom x c → Cc.Hom y c
              → Dc.Hom (App₀ x) (App₀ y) → Cc.Hom x y

  -- The global form implies every anchored form.
  Reflect : Type ℓ
  Reflect = {x y : Cc.Ob} → Dc.Hom (App₀ x) (App₀ y) → Cc.Hom x y

  reflect→at : Reflect → (c : Cc.Ob) → ReflectAt c
  reflect→at r c gx gy m = r m

  -- The coarse sieve generated by the image of a fine sieve.
  imageSieve : (c : Cc.Ob) → Sieve {C = C} c → Sieve {C = D} (App₀ c)
  imageSieve c T = mem , clo
    where
    mem : (d' : Dc.Ob) → Dc.Hom d' (App₀ c) → hProp ℓ
    mem d' h =
      ∥ Σ[ e ∈ Cc.Ob ] Σ[ g ∈ Cc.Hom e c ]
          (fst (fst T e g) ×
           (Σ[ m ∈ Dc.Hom d' (App₀ e) ] (h ≡ m Dc.⋆ App₁ g))) ∥₁
      , squash₁
    clo : Closure {C = D} (App₀ c) mem
    clo d' e'' k h = PT.map λ { (e , g , t , m , q) →
        e , g , t , (k Dc.⋆ m) ,
        (cong (k Dc.⋆_) q ∙ sym (Dc.⋆-assoc k m (App₁ g))) }

-- ------------------------------------------------------------
-- Tier 1: BackCond∥, with D thin.
-- ------------------------------------------------------------
module _ {ℓ} {C D : Precategory ℓ ℓ} (F : BaseFunctor C D)
         (thinD : (x y : Precategory.Ob D) → isProp (Precategory.Hom D x y)) where
  private
    module Cc = Precategory C
    module Dc = Precategory D
  open BaseFunctor F

  private
    -- Move a membership along an object path.  Thinness of D
    -- matches the arrows over the path.
    mem-move : {w : Dc.Ob} (S : Sieve {C = D} w) {x y : Dc.Ob} (p : x ≡ y)
               (hx : Dc.Hom x w) (hy : Dc.Hom y w)
             → fst (fst S x hx) → fst (fst S y hy)
    mem-move {w} S p hx hy m =
      transport (λ i → fst (fst S (p i)
                        (isProp→PathP (λ j → thinD (p j) w) hx hy i))) m

  -- ----------------------------------------------------------
  -- φB is injective: a coarse sieve is recovered from its
  -- preimage through the lifts.
  -- ----------------------------------------------------------
  φB-inj : BackCond∥ F → (c : Cc.Ob) (S T : Sieve {C = D} (App₀ c))
         → φB F c S ≡ φB F c T → S ≡ T
  φB-inj back c S T p = Sieve≡ {C = D} S T (funExt λ d' → funExt λ h →
      PT.rec (isSetHProp (fst S d' h) (fst T d' h)) (go d' h) (back c d' h))
    where
    go : (d' : Dc.Ob) (h : Dc.Hom d' (App₀ c))
       → Σ[ e' ∈ Cc.Ob ] Σ[ k ∈ Cc.Hom e' c ] (App₀ e' ≡ d')
       → fst S d' h ≡ fst T d' h
    go d' h (e' , k , q) = ⇔toPath
      (λ m → mem-move T q (App₁ k) h
               (transport (λ i → fst (fst (p i) e' k))
                          (mem-move S (sym q) h (App₁ k) m)))
      (λ m → mem-move S q (App₁ k) h
               (transport (λ i → fst (fst (p (~ i)) e' k))
                          (mem-move T (sym q) h (App₁ k) m)))

  -- ----------------------------------------------------------
  -- φB commutes with Heyting implication.  The forward
  -- direction holds for every F.  The backward direction reads
  -- a coarse refinement through its lift, which BackCond∥
  -- supplies.
  -- ----------------------------------------------------------
  φB-⇒ : BackCond∥ F → (c : Cc.Ob) (S T : Sieve {C = D} (App₀ c))
       → φB F c (_⇒S_ {C = D} {c = App₀ c} S T)
       ≡ _⇒S_ {C = C} {c = c} (φB F c S) (φB F c T)
  φB-⇒ back c S T = Sieve≡ {C = C} _ _ (funExt λ d → funExt λ f → go d f)
    where
    go : (d : Cc.Ob) (f : Cc.Hom d c)
       → fst (φB F c (_⇒S_ {C = D} {c = App₀ c} S T)) d f
       ≡ fst (_⇒S_ {C = C} {c = c} (φB F c S) (φB F c T)) d f
    go d f = ⇔toPath fwd bwd
      where
      fwd : ((e : Dc.Ob) (g : Dc.Hom e (App₀ d))
              → fst (fst S e (g Dc.⋆ App₁ f)) → fst (fst T e (g Dc.⋆ App₁ f)))
          → ((e : Cc.Ob) (g : Cc.Hom e d)
              → fst (fst S (App₀ e) (App₁ (g Cc.⋆ f)))
              → fst (fst T (App₀ e) (App₁ (g Cc.⋆ f))))
      fwd L e g m =
        subst (λ h → fst (fst T (App₀ e) h)) (sym (App-⋆ g f))
              (L (App₀ e) (App₁ g)
                 (subst (λ h → fst (fst S (App₀ e) h)) (App-⋆ g f) m))
      bwd-lift : (d' : Dc.Ob) (h : Dc.Hom d' (App₀ d))
               → ((e : Cc.Ob) (g : Cc.Hom e d)
                   → fst (fst S (App₀ e) (App₁ (g Cc.⋆ f)))
                   → fst (fst T (App₀ e) (App₁ (g Cc.⋆ f))))
               → Σ[ e' ∈ Cc.Ob ] Σ[ k ∈ Cc.Hom e' d ] (App₀ e' ≡ d')
               → fst (fst S d' (h Dc.⋆ App₁ f)) → fst (fst T d' (h Dc.⋆ App₁ f))
      bwd-lift d' h R (e' , k , q) m =
        mem-move T q (App₁ k Dc.⋆ App₁ f) (h Dc.⋆ App₁ f)
          (subst (λ h' → fst (fst T (App₀ e') h')) (App-⋆ k f)
            (R e' k
              (subst (λ h' → fst (fst S (App₀ e') h')) (sym (App-⋆ k f))
                (mem-move S (sym q) (h Dc.⋆ App₁ f) (App₁ k Dc.⋆ App₁ f) m))))
      bwd : ((e : Cc.Ob) (g : Cc.Hom e d)
              → fst (fst S (App₀ e) (App₁ (g Cc.⋆ f)))
              → fst (fst T (App₀ e) (App₁ (g Cc.⋆ f))))
          → ((e : Dc.Ob) (g : Dc.Hom e (App₀ d))
              → fst (fst S e (g Dc.⋆ App₁ f)) → fst (fst T e (g Dc.⋆ App₁ f)))
      bwd R d' h m =
        PT.rec (snd (fst T d' (h Dc.⋆ App₁ f)))
               (λ l → bwd-lift d' h R l m)
               (back d d' h)

  -- Negation is implication into ⊥, so it transfers too.
  φB-¬ : BackCond∥ F → (c : Cc.Ob) (S : Sieve {C = D} (App₀ c))
       → φB F c (¬S {C = D} {c = App₀ c} S) ≡ ¬S {C = C} {c = c} (φB F c S)
  φB-¬ back c S =
    φB-⇒ back c S (⊥S {C = D} (App₀ c))
    ∙ cong (λ Z → _⇒S_ {C = C} {c = c} (φB F c S) Z) (φB-⊥ F c)

  -- ----------------------------------------------------------
  -- Tier 2: add ReflectAt, with C thin.  imageSieve is a
  -- two-sided inverse of φB.
  -- ----------------------------------------------------------
  module _ (thinC : (x y : Cc.Ob) → isProp (Cc.Hom x y)) where

    φB-surjective : (c : Cc.Ob) → ReflectAt F c → (T : Sieve {C = C} c)
                  → φB F c (imageSieve F c T) ≡ T
    φB-surjective c down T = Sieve≡ {C = C} _ _
        (funExt λ e' → funExt λ g' → go e' g')
      where
      go : (e' : Cc.Ob) (g' : Cc.Hom e' c)
         → fst (φB F c (imageSieve F c T)) e' g' ≡ fst T e' g'
      go e' g' = ⇔toPath
        (PT.rec (snd (fst T e' g'))
          (λ { (e , g , t , m , q) →
               subst (λ w → fst (fst T e' w)) (thinC e' c (down g' g m Cc.⋆ g) g')
                     (snd T e e' (down g' g m) g t) }))
        (λ t → ∣ e' , g' , t , Dc.idn , sym (Dc.⋆-idL (App₁ g')) ∣₁)

    φB-retract : BackCond∥ F → (c : Cc.Ob) → ReflectAt F c
               → (S : Sieve {C = D} (App₀ c))
               → imageSieve F c (φB F c S) ≡ S
    φB-retract back c down S =
      φB-inj back c (imageSieve F c (φB F c S)) S
             (φB-surjective c down (φB F c S))
